### ISSUE TITLE
License to use api code

### ISSUE THREAD

**Issue by Jens-Co** [aternosorg/mclogs-java#2]
Hello there,

got a question about which License this repo is on. Since The mc logs api class is something I would like to use in our repo ( https://github.com/GeyserMC/Geyser) to make html requests I'm I allowed to do so ? 

Thanks in forward,
Jens

**Comment by matthi4s** [comment]
Hey, thanks for the question, we forgot to add the license file. It should be licensed under the MIT license like our other projects, so feel free to use it wherever you want. We'll add the license file as soon as we can.

**Comment by JulianVennen** [comment]
The MIT License has been added to the repo
