### ISSUE TITLE
How to use in project?

### ISSUE THREAD

**Issue by Skyslycer** [aternosorg/mclogs-java#6]
Hi, I wanted to include such an upload feature for ages now and I stumbled upon this beautiful library. But it isn't published anywhere (please do this, it's really, really simple) so I would have to copy the files.

My question is, how do I do that legally? My project is AGPL, so should I add MIT license headers or what do I have to add in order to be compliant?

Kind regards and please answer soon,
Sky

**Comment by Skyslycer** [comment]
And am I allowed to publish this on my own maven repository so I don't have to copy the classes every time?

**Comment by JulianVennen** [comment]
Hi, thanks for reaching out.
We do plan on publishing this to maven central, and already claimed the namespace for it.
We currently use git submodules to import this in other projects we use (e.g. [our bukkit plugin](https://github.com/aternosorg/mclogs-bukkit))
Alternatively, you could pull the releases from JitPack: https://jitpack.io/

> My project is AGPL, so should I add MIT license headers or what do I have to add in order to be compliant?

I'm not a lawyer, but you would probably need to include a notice that you use our library and that the library is licensed as MIT.

> am I allowed to publish this on my own maven repository

Yes

**Comment by JulianVennen** [comment]
It's now published on maven central.
I also decided to do some refactoring and release a v3.0.0 version: https://github.com/aternosorg/mclogs-java/releases/tag/3.0.0

It's probably going to take about an hour for that to actually sync to central, but the instructions for using it are in the readme: https://github.com/aternosorg/mclogs-java#usage
